
name: Run Script on Dev Push


on:
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: self-hosted
    # dirTest is now a GitHub repository variable, not defined here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'
      - name: Print RPA_TEST secret
        run: echo RPA_TEST=%RPA_TEST%
        shell: cmd
        env:
          RPA_TEST: ${{ secrets.RPA_TEST }}
      - name: Pull latest code
        run: |
          cd ${{ vars.dirTest }}
          git pull origin dev
        shell: cmd
      - name: Run script
        run: |
          cd ${{ vars.dirTest }}
          C:\Users\freel\AppData\Local\Microsoft\WindowsApps\python.exe run.py
        shell: cmd
